name: Clojure CI

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload to clojars
      run: lein deploy snapshots
      env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWD: ${{ secrets.CLOJARS_PASSWD }}
  
